# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('possiblebug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, related_name='_author_test_+', to='possiblebug.Author'),
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='test',
        ),
        migrations.AddField(
            model_name='publisher',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_publisher_test_models', to='possiblebug.Publisher'),
        ),
    ]
